live-player-markers: true
hidden-game-modes: ["spectator"]
hide-vanished: true
hide-invisible: true
hide-sneaking: false
hide-below-sky-light: 0
hide-below-block-light: 0
hide-different-world: true
skin-download: true

# Never compete with active players for render CPU.
player-render-limit: 1
full-update-interval: 1440
