enabled: true
webroot: "bluemap/web"
update-settings-file: true
use-cookies: true
default-to-flat-view: false
min-zoom-distance: 5
max-zoom-distance: 100000
resolution-default: 2
hires-slider-min: 0
hires-slider-default: 250
hires-slider-max: 750
lowres-slider-min: 500
lowres-slider-default: 3000
lowres-slider-max: 10000
scripts: []
styles: []
